### ISSUE TITLE
Issues Packaging vSRX

### ISSUE THREAD

**Issue by tagur87** [carlmontanari/boxen#1]
Hi @carlmontanari

Thanks for posting this wonderful project. This is something we would love use for packaging a vSRX image into a docker container for some automated testing and validation.

I am running into an issue when trying to package a vSRX image in qcow2 format. Is there something I am doing wrong that is causing the error below?

```
boxen package --disk junos-media-vsrx-x86-64-vmdisk-20.3R3.8.qcow2 
      info   1641225460 package requested for disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.qcow2'
  critical   1641225460 failed gleaning source data from disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.qcow2'
  critical   1641225460 error allocating disks for packaging: inspectionError: failed gleaning source data from disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.qcow2'
        🆘 finished unsuccessfully in 0 seconds 
inspectionError: failed gleaning source data from disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.qcow2'
```

I also tried ova format, bu that did not work either.

```
boxen package --disk junos-media-vsrx-x86-64-vmdisk-20.3R3.8.ide.ova
      info   1641226635 package requested for disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.ide.ova'
  critical   1641226635 failed gleaning source data from disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.ide.ova'
  critical   1641226635 error allocating disks for packaging: inspectionError: failed gleaning source data from disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.ide.ova'
        🆘 finished unsuccessfully in 0 seconds 
inspectionError: failed gleaning source data from disk 'junos-media-vsrx-x86-64-vmdisk-20.3R3.8.ide.ova'
````

**Comment by tagur87** [comment]
Actuall looks like this line may be to blame. https://github.com/carlmontanari/boxen/blob/98a32ca384635b77bbccaaeb0a4b99460022fc91/boxen/platforms/util.go#L16

May need to improve the regex matching string to follow the pattern of files downloaded for juniper in recent versions.

**Comment by carlmontanari** [comment]
Hey @tagur87 yeah the patterns are not super broad and really just match the things I had available. Do you know if all the more recent disk images follow the same pattern as that qcow you have in the output above? if so I can prolly get that updated and pushed up later today/tonight, and can release 0.0.1 later this week.

Thanks for raising this!

Carl

**Comment by tagur87** [comment]
Yea from what I can see, the most recent vSRX images follow this pattern `junos-media-vsrx-x86-64-vmdisk-20.3R1.8.qcow2`

**Comment by carlmontanari** [comment]
Hey @tagur87 

How does this pattern look to ya: `(?:junos-)?media-vsrx-(?:x86-64-)?vmdisk.*.qcow2` should match the older 17.x one I have to test with and this new disk. I'll plan to add the capability to explicitly pass the target vendor/platform as well (overriding the auto-selection thing) at some point but probably won't get to that till the weekend.

Thanks for the help on this!

Carl

**Comment by carlmontanari** [comment]
Simpler pattern in linked pr, lemme know what ya think!

**Comment by tagur87** [comment]
Yea that pattern looks good and matches the file I downloaded from juniper the other day! Thanks for your efforts on this!

**Comment by jsakofsky** [comment]
hola! found this and see the change in regex was merged but i seem to be hitting the issue as well:
```
# boxen package --disk ~/disks/junos-media-vsrx-x86-64-vmdisk-21.2R2-S1.5.qcow2 
      info   1642523309 package requested for disk '/root/disks/junos-media-vsrx-x86-64-vmdisk-21.2R2-S1.5.qcow2'
  critical   1642523309 failed gleaning source data from disk '/root/disks/junos-media-vsrx-x86-64-vmdisk-21.2R2-S1.5.qcow2'
  critical   1642523309 error allocating disks for packaging: inspectionError: failed gleaning source data from disk '/root/disks/junos-media-vsrx-x86-64-vmdisk-21.2R2-S1.5.qcow2'
	🆘 finished unsuccessfully in 0 seconds 
inspectionError: failed gleaning source data from disk '/root/disks/junos-media-vsrx-x86-64-vmdisk-21.2R2-S1.5.qcow2'
```
i've tried renaming the file but the regex should be matching it so unsure whats happening here. running 0.0.1, but also tried the 0.0.1-alpha to be safe and same thing.
`# boxen --version
	version: 0.0.1
	source: https://github.com/carlmontanari/boxen`

**Comment by carlmontanari** [comment]
Hey @jsakofsky juniper version numbers make me sad (to be fair, most vendors version numbers make me sad!). Looks like the vendor -> platform regex works, but the regex to glean the disk version is missing the `-` in the number-y part. At some point I swear I will add tests for this stuff... but ya know, time and all that :) Anyway, will push something that should match to main here in a bit and update this comment so you can try to build from there.

PS- I dont think you'll need to do this because the only time we do the version parsing stuff is in the "outer" boxen (the part you run on your machine, not int he container), but if im forgetting that the stuff in the container does any of this regex checking you can use [this](https://github.com/carlmontanari/boxen#packaging-with-non-release-versions) to include the locally built boxen in the container instead of yanking from GitHub releases.

**Comment by hellt** [comment]
@carlmontanari isn't user-defined platform flag the answer to that?

**Comment by carlmontanari** [comment]
Haha just was about to add another comment -- yeah... what @hellt said -- *should* also work with passing the `--vendor` `--platform` and `--version` flags to `package`. If memory serves you have to pass all three as we basically explicitly ignore the auto finding stuff! Good call Roman!

**Comment by jsakofsky** [comment]
excellent, the flags did the needful. thanks so much all, all around.

**Comment by carlmontanari** [comment]
awesome, thanks for confirming @jsakofsky and thanks @hellt for chiming in!
