### ISSUE TITLE
is `boxenGlobalFlags()` the correct name of a function?

### ISSUE THREAD

**Issue by hellt** [carlmontanari/boxen#13]
https://github.com/carlmontanari/boxen/blob/00e2c9b0ffe39bf74b47faeece907702b00030ff/boxen/cli/cli.go#L11

it seems like this function specifically creates the `config` CLI flag structure. Should it rather be naned `boxenConfigFlag`?

**Comment by hellt** [comment]
ah, it seems this function is created with an outlook for the future, when more global flags can pop up...
I'll close this then, unless you may have wanted to address this.

**Comment by carlmontanari** [comment]
Yeah that’s the idea! Obviously a little lonely right now though 🙃
