### ISSUE TITLE
Cannot package Nexus 9000v 10.2(2)F qcow2 file

### ISSUE THREAD

**Issue by ChristopherJHart** [carlmontanari/boxen#25]
On an Ubuntu 20.04 virtual machine (running on VirtualBox), I am unable to use `boxen package` to package the NX-OS 10.2(2)F Nexus 9000v qcow2 file.

```
christopher@ubuntu-playground:~/Downloads$ BOXEN_DEBUG_LEVEL=debug BOXEN_DEV_MODE=1 boxen package --disk ~/Downloads/nexus9300v64.10.2.2.F.qcow2
      info   1648075996 package requested for disk '/home/christopher/Downloads/nexus9300v64.10.2.2.F.qcow2'
  critical   1648075996 failed gleaning source data from disk '/home/christopher/Downloads/nexus9300v64.10.2.2.F.qcow2'
  critical   1648075996 error allocating disks for packaging: inspectionError: failed gleaning source data from disk '/home/christopher/Downloads/nexus9300v64.10.2.2.F.qcow2'
        🆘 finished unsuccessfully in 0 seconds
inspectionError: failed gleaning source data from disk '/home/christopher/Downloads/nexus9300v64.10.2.2.F.qcow2'
```

Digging through the code, I think this is due to the regular expression pattern here: https://github.com/carlmontanari/boxen/blob/6a3cf944e80d8ac1f9995ef75dd4a3a6f7998e82/boxen/platforms/util.go#L59

This pattern doesn't match the filename `nexus9300v64.10.2.2.F.qcow2`. I think the following regular expression pattern should work:

```
(?i)(?:(?:nexus9300v(?:64)?|nxosv)\.)(\d+\.\d+\.\d+)
```

**Comment by carlmontanari** [comment]
Blah, too many filenames to keep up with!

Open to a quick PR to add that? In the meantime you can package and explicitly pass the vendor/platform/version so the regex resolution stuff doesn't need to happen!

Carl

**Comment by ChristopherJHart** [comment]
I created PR #26 to fix this. Be forewarned, this PR and its changes were not tested - I don't anything about how to compile Go applications (You know I love my Python *way* too much to be unfaithful 😅). If you need me to, I can do some research later today about how to compile Go and test these changes.

**Comment by carlmontanari** [comment]
haha cool, will close this and pick it up over in the pr then!
