### ISSUE TITLE
Boxen update script references containerlab release notes

### ISSUE THREAD

**Issue by ChristopherJHart** [carlmontanari/boxen#36]
When the Boxen update Bash script (`get.sh`) detects a new Boxen update is available, it references Containerlab release notes.
```
christopher@ubuntu-vm:~$ bash -c "$(curl -sL https://raw.githubusercontent.com/carlmontanari/boxen/main/get.sh)"
No help topic for 'version'
A newer boxen 0.0.3 is available. Release notes: https://containerlab.srlinux.dev/rn/0.0.3    <<<
You are running containerlab  version
Proceed with upgrade? [Y/n]: Y
Downloading https://github.com/carlmontanari/boxen/releases/download/v0.0.3/boxen_0.0.3_linux_amd64.tar.gz
Preparing to install boxen 0.0.3 into /usr/local/bin
boxen installed into /usr/local/bin/boxen
        version: 0.0.3
        source: https://github.com/carlmontanari/boxen
```
For now (in my opinion of course), we should probably point users to the [project's GitHub releases page](https://github.com/carlmontanari/boxen/releases/latest) (which contains a list of changes made between versions).

I'll get a PR opened up to fix this!

**Comment by hellt** [comment]
Lol @carlmontanari

**Comment by carlmontanari** [comment]
hahah thank you so much @ChristopherJHart ! @hellt I am making a living on copying you on GitHub 😁
