### ISSUE TITLE
Pan-Os issue using the image with containerlab

### ISSUE THREAD

**Issue by BouchardClaude** [carlmontanari/boxen#41]
Hi!, I'm trying to package PanOs for containerlab and im facing some issue. not sure If I missed a step ?
I did package with Sparsify  on using vendor paloalto and platform panos and I see the docker image :
![image](https://user-images.githubusercontent.com/22671885/201210853-706ed7a4-0d32-4e1b-bf2c-e922fc5af25d.png)

But when I try to use is with containerlab or by itself, the docker crash with this log:

```
Incorrect Usage: flag provided but not defined: -username

NAME:
   boxen package-install - install/finalize a vm instance packaging in a container

USAGE:
   boxen package-install [command options] [arguments...]

OPTIONS:
   --help, -h  show help (default: false)
   
flag provided but not defined: -username
```

did I miss a step?

Thanks

**Comment by carlmontanari** [comment]
*something* definitely went wrong there, but very possibly nothing you did wrong!

I think more than one thing went wrong there probably. IIRC with sparsity the image should be smaller than that as well as obviously working correctly.

I'll be honest with you, you are probably on your own (or any community love) for troubleshooting this as I don't have a PAN image, nor have any reason to mess with one anymore -- and, on top of that, it has been nothing but a PITA :). I know folks have had issues w/ this image, but I also know people not me have succeeded so it should be possible! 

All that said, probably wanna re-run like below and get allllll the logs and hopefully something obvious will pop out:

`BOXEN_LOG_LEVEL=debug BOXEN_DEV_MODE=1 boxen package --disk ~/disks/nxosv.9.2.4.qcow2`

Log level is obvious of course, the dev mode will make sure to *not* nuke the temp build directory so you can grab logs and inspect stuff if it fails.

Good luck!

**Comment by BouchardClaude** [comment]
Thx @carlmontanari for the quick reply.  the DEV mode is helping me as I can check the build log afterward. 
I'm not sure ill be able to fix it but ill give it a try

thanks to your explanation I was able to understand that the initial build looked fine and the issue is when the intermediate docker is executed to build the final one. 
The docker is crashing as soon it is started, and ill be focusing on figuring out why.
If you dont mind explaning me this line, I think it would help :

does the "launching instance with command" refer to lunching the docker with thoses arg, or Qemu inside of the docker?

```
     debug   1668275043 base image building complete!
     debug   1668275044 package install starting
     debug   1668275044 begin instance install
      info   1668275044 install requested
      info   1668275044 qemu instance start requested
     debug   1668275044 launching instance with command: [-name paloalto_panos -uuid 50f5d398-77cd-49cc-a468-3ebb31ce28ac -accel kvm -display none -machine pc -m 8192 -cpu host -smp cores=1,threads=1,sockets=2 -monitor tcp:0.0.0.0:4001,server,nowait -serial telnet:0.0.0.0:5001,server,nowait -drive if=ide,file=disk.qcow2,format=qcow2 -device pci-bridge,chassis_nr=1,id=pci.1 -device virtio-net-pci,netdev=mgmt -netdev user,id=mgmt,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::48000-10.0.0.15:22,hostfwd=tcp::48001-10.0.0.15:23,hostfwd=tcp::48002-10.0.0.15:443,hostfwd=tcp::48003-10.0.0.15:830,hostfwd=udp::48004-10.0.0.15:161 -device virtio-net-pci,netdev=p001,bus=pci.1,addr=0x2,mac=52:54:00:0c:8c:01 -netdev socket,id=p001,listen=:10001 -device virtio-net-pci,netdev=p002,bus=pci.1,addr=0x3,mac=52:54:00:62:c6:02 -netdev socket,id=p002,listen=:10002 -device virtio-net-pci,netdev=p003,bus=pci.1,addr=0x4,mac=52:54:00:e4:7f:03 -netdev socket,id=p003,listen=:10003 -device virtio-net-pci,netdev=p004,bus=pci.1,addr=0x5,mac=52:54:00:32:79:04 -netdev socket,id=p004,listen=:10004 -device virtio-net-pci,netdev=p005,bus=pci.1,addr=0x6,mac=52:54:00:15:03:05 -netdev socket,id=p005,listen=:10005 -device virtio-net-pci,netdev=p006,bus=pci.1,addr=0x7,mac=52:54:00:dc:5c:06 -netdev socket,id=p006,listen=:10006 -device virtio-net-pci,netdev=p007,bus=pci.1,addr=0x8,mac=52:54:00:45:d8:07 -netdev socket,id=p007,listen=:10007 -device virtio-net-pci,netdev=p008,bus=pci.1,addr=0x9,mac=52:54:00:57:b5:08 -netdev socket,id=p008,listen=:10008 -device virtio-net-pci,netdev=p009,bus=pci.1,addr=0xa,mac=52:54:00:61:d4:09 -netdev socket,id=p009,listen=:10009]
     debug   1668275044 stdout logger provided, setting execute argument
     debug   1668275044 stderr logger provided, setting execute argument
      info   1668275054 qemu instance start complete
     debug   1668275054 instance started, waiting for start ready state
      info   1668275063 install logs available at '/tmp/boxen3404509520/install_build.log', or by inspect container 'ae8cd44cce1fc7beb7e29efc4d1d7980079f9bb80e5c554c9679f1bc19040366' logs
  critical   1668275064 package installation failed: instanceError: process already exited
  critical   1668275065 error running instance installation: commandError: docker wait indicates install container exited with non-zero exit code

```

anyway, feel free to close the ticket if you want, as I dont think its related to boxen, but more with something very specific of palo.. :)

**Comment by carlmontanari** [comment]
`launching instance with command` is the emu command inside the container IIRC! because after the initial packaging (build base image, copy files in, copy boxen executable in, etc.) we then have to launch the image in the container so we can then get through initial config dialog and then save the image!

> as I dont think its related to boxen, but more with something very specific of palo

heh, it may be a little of both! but I'm sure you'll get it sorted!

I'll close it out but feel free to reopen if there's a boxen related thing. im happy to review prs and get them merged, just not having much time/energy for active dev here. Thanks a bunch @BouchardClaude !

Carl

**Comment by hellt** [comment]
Hey @BouchardClaude 
when you see this string in the logs `install logs available at '/tmp/boxen3404509520/install_build.log'` you should tail that log file and see what happens during the install, it might contain some more verbose error messages to understand whats causing the process to exit prematurely

**Comment by BouchardClaude** [comment]
thx @hellt  , I was actually looking at this ! 
Unfortunalty it only show 
```
# cat /tmp/boxen3404509520/install_build.log
instanceError: process already exited
```

but then I tried to execute the container by itself with no args just to see if it would start and at leas crash with a more explicit error and I got this, So ill be looking on this side a bit see if its normal.

```
# docker run  ce0480971a65 
panic: could not setup socket sender

goroutine 1 [running]:
github.com/carlmontanari/boxen/boxen/cli.packageInstall()
        /home/runner/work/boxen/boxen/boxen/cli/packageinstall.go:42 +0x25a
github.com/carlmontanari/boxen/boxen/cli.packageInstallCommands.func1(0xc00007bd70?)
        /home/runner/work/boxen/boxen/boxen/cli/packageinstall.go:22 +0x17
github.com/urfave/cli/v2.(*Command).Run(0xc0000eaea0, 0xc00007ea00)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc0000bfa00, {0xa3d1d0?, 0xc00002c030}, {0xc000020040, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/boxen/boxen/main.go:13 +0x45
```

thx for the hint !

**Comment by BouchardClaude** [comment]
let me try to package a veos or something else and see if I hit the same issue.. at least ill know if its related to my image or not!

**Comment by carlmontanari** [comment]
`panic: could not setup socket sender` this is related to streaming logs from in the build container back to your machine... what OS are you running on? I wonder if some firewall-y magic is breaking that?

**Comment by BouchardClaude** [comment]
Sorry for the delay


Ubuntu 22
# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
# sudo ufw status
Status: inactive
# sudo docker --version
Docker version 20.10.21, build baeda1f

What OS are you using? I can Test with the same setup..

**Comment by BouchardClaude** [comment]
I just tested with vEOS and it is working just fine !  So its someting that is only triggered by the panos build.

I'm using Ubuntu 22 LTS with firewall off , by chance do you know what os you use.. I can try the same and see if I get any luck.

thx for the help.

**Comment by carlmontanari** [comment]
Interesting! I've built it on macOS (whatever is latest version), and on ubuntu 22 boxes (also ufw disabled).

the socket setup in theory should be super simple, things happen [here](https://github.com/carlmontanari/boxen/blob/98a32ca384635b77bbccaaeb0a4b99460022fc91/boxen/cli/packageinstall.go#L40-L42) and [here](https://github.com/carlmontanari/boxen/blob/98a32ca384635b77bbccaaeb0a4b99460022fc91/boxen/logging/socketsender.go#L35) -- you could add some more printing/checking around those places to try to see whats what maybe...

**Comment by hellt** [comment]
so this socket stuff is the same in every other image build process I presume,
so that error in panos is likely happening because some shit happened before it.

What may help you is to make sure that when you try and build panos, you clean up any stale containers with panos name that might be leftovers from previous runs.
I vaguely remember that I had issues with boxen (or rather maybe docker) not overwriting container images when I did multiple consequent build attempts.
So I added a hard clean up command to make sure everything is wiped off

```
docker rmi -f boxen_${FULLPLATFORM}:${VERSION} && \
rm -rf /tmp/boxen* && \
docker ps -a -q | xargs -n1 docker rm
```

**Comment by carlmontanari** [comment]
good call -- I think there is a possibility of problems because the layers aren't like "normal" layers since we just build the base image then run it and copy stuff into it. so if we have a "bad" (for whatever reason) base image things can be broken and really difficult to see why!

**Comment by BouchardClaude** [comment]
Here are some news..
I did recompile the code with some print ( never touched go before, so I did learn some stuff ! )
and sent the version compiled with prints ( I used fmt, not sure better way to print out? ) to the intermediate docker to catch the error. I got:
```
root@7e0a7eb33623:/# ./boxen package-install
dial tcp 10.191.2.175:6667: connect: connection refused&{0xc0000b1d40 <nil>}error creating socket connection
```
So I really try to make the connection to the host on port 6667, but that make me confuse as I'm expecting it to do it on port 6666 ? ( I did observe that boxen is staying on port 6666 )
![image](https://user-images.githubusercontent.com/22671885/201548338-cc7ea033-6f54-4b96-9f04-9fe7aaecb46d.png)

is it just the wrong port or boxen on my host is suppose to spin another process listening on 6667 ?

thanks!

**Comment by carlmontanari** [comment]
yeah, boxen on your host spins up a listening port, then we stream the logs from the container back to your host so you can watch the logs while it does its thing.

**Comment by BouchardClaude** [comment]
oh good to know, Ill try to figure out why I never saw 6667 on my netstats on the host then, It make sens that the docker is crashing if the port is just not listening !

**Comment by BouchardClaude** [comment]
![image](https://user-images.githubusercontent.com/22671885/201549654-d7a17c48-20ea-4e99-ab8e-6c27da2418d2.png)
just to correct my previous post : I  was wrong, it does listen on 6667 ( just for a moment ) .. 
but its binded on the external ip address instead of listening on all ip like 6666. I wonder if its not Something related to docker nating the ip ...

**Comment by BouchardClaude** [comment]
Good news ! I figured out the issue, and it had really nothing to do with the logger.
I look like qemu was crashing right at start, leaving no time for any other process. 

I tried to start Qemu with the same args from the debug on the host and saw it crashing with 
`kvm_buf_set_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed`
After some research, i found this was a bug with nested virtualization, and after activating the cpu counter on the hypervisor, qemu was able to start properly.

now, I have new error with console read timeout  , but i now really feel that they are specific to palo alto, and that we can close this issue. ill work on those on my side and if I find any specific fix ill publish them on another topic.

Thanks @carlmontanari  and @hellt for the help ! sorry for the bad path of the logguer. at least I did learn some go !

**Comment by carlmontanari** [comment]
Very nice detective work!! I think ultimately my crappy logger implementation is probably the culprit here! It doesn’t flush logs properly before things quit which made this harder on you. One of these days I’ll fix it … :)

anyway, I’m glad you have made some progress, and thank you a ton for reporting it all here! Good luck with the rest and let us know if anything else comes up!
