### ISSUE TITLE
Add requirements part

### ISSUE THREAD

**Issue by jmanteau** [carlmontanari/boxen#8]
Boxen needs mkisofs.
It should precised into the README

On Mac, I had to do ```brew install cdrtools```

**Comment by carlmontanari** [comment]
yep! its on a todo list somewhere.... boxen is sorely lacking docs but haven't had the time yet. thanks for opening this!

**Comment by hellt** [comment]
I think we have two better alternatives

1) check if go community came up with a package that can do what we use mkisofs for
2) if 1 is not an option, use containerized mkisofs (that adds a requirement to have docker/podman, but it is more sane, than asking do download a binary for a one-off use)

**Comment by carlmontanari** [comment]
Oh I really like option 2, *but* this is also a requirement for "local" mode -- where we may not need/want/have docker/podman. Dunno how I feel about requiring docker for the local mode, but for the other way I love it (but there is no way to know which mode you are doing where the cdrtools thing is needed).... so, option 1 seems worth investigating. will leave this open for reminder for both docs and to try to make it smoother in general via one of these paths! Thanks Roman (as per usual!)!

**Comment by hellt** [comment]
yup, I think the easiest way is opt2
and we can (in boxen) check if docker is installed, if yes - the mkisofs command becomes `sudo docker run ... mkisofs`, otherwise, just `mkisofs`

**Comment by hellt** [comment]
@jmanteau in #22 I tried to fix that issue by using mkisofs in a container if it was not found locally

you can get a binary with the fix by running the following command

```
docker run --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v0.12.0 pull  ttl.sh/boxen-bd8c238:1d
```
